const data = [
  {
    id: 1,
    AverageHomePricePoint: "$100K-$200K",
    PlanName: "Qualified 20",
    QualifiedLeadsPerMonth: 20,
    PricePerLiveTransfer: 69,
    TotalQualifiedLeadPrice: 1380,
    TotalPlatformPrice: 299,
    FinalPackagePrice: 1679,
  },
  {
    id: 2,
    AverageHomePricePoint: "$100K-$200K",
    PlanName: "Qualified 40",
    QualifiedLeadsPerMonth: 40,
    PricePerLiveTransfer: 67,
    TotalQualifiedLeadPrice: 2680,
    TotalPlatformPrice: 599,
    FinalPackagePrice: 3279,
  },
  {
    id: 3,
    AverageHomePricePoint: "$100K-$200K",
    PlanName: "Qualified 60",
    QualifiedLeadsPerMonth: 60,
    PricePerLiveTransfer: 65,
    TotalQualifiedLeadPrice: 3900,
    TotalPlatformPrice: 699,
    FinalPackagePrice: 4599,
  },
  {
    id: 4,
    AverageHomePricePoint: "$100K-$200K",
    PlanName: "Qualified 80",
    QualifiedLeadsPerMonth: 80,
    PricePerLiveTransfer: 63,
    TotalQualifiedLeadPrice: 5040,
    TotalPlatformPrice: 799,
    FinalPackagePrice: 5839,
  },
  {
    id: 5,
    AverageHomePricePoint: "$200K-$300K",
    PlanName: "Qualified 20",
    QualifiedLeadsPerMonth: 20,
    PricePerLiveTransfer: 79,
    TotalQualifiedLeadPrice: 1580,
    TotalPlatformPrice: 299,
    FinalPackagePrice: 1879,
  },
  {
    id: 6,
    AverageHomePricePoint: "$200K-$300K",
    PlanName: "Qualified 40",
    QualifiedLeadsPerMonth: 40,
    PricePerLiveTransfer: 77,
    TotalQualifiedLeadPrice: 3080,
    TotalPlatformPrice: 599,
    FinalPackagePrice: 3679,
  },
  {
    id: 7,
    AverageHomePricePoint: "$200K-$300K",
    PlanName: "Qualified 60",
    QualifiedLeadsPerMonth: 60,
    PricePerLiveTransfer: 74,
    TotalQualifiedLeadPrice: 4440,
    TotalPlatformPrice: 699,
    FinalPackagePrice: 5139,
  },
  {
    id: 8,
    AverageHomePricePoint: "$200K-$300K",
    PlanName: "Qualified 80",
    QualifiedLeadsPerMonth: 80,
    PricePerLiveTransfer: 72,
    TotalQualifiedLeadPrice: 5760,
    TotalPlatformPrice: 799,
    FinalPackagePrice: 6559,
  },
  {
    id: 9,
    AverageHomePricePoint: "$300K-$400K",
    PlanName: "Qualified 20",
    QualifiedLeadsPerMonth: 20,
    PricePerLiveTransfer: 99,
    TotalQualifiedLeadPrice: 1980,
    TotalPlatformPrice: 299,
    FinalPackagePrice: 2279,
  },
  {
    id: 10,
    AverageHomePricePoint: "$300K-$400K",
    PlanName: "Qualified 40",
    QualifiedLeadsPerMonth: 40,
    PricePerLiveTransfer: 96,
    TotalQualifiedLeadPrice: 3840,
    TotalPlatformPrice: 599,
    FinalPackagePrice: 4439,
  },
  {
    id: 11,
    AverageHomePricePoint: "$300K-$400K",
    PlanName: "Qualified 60",
    QualifiedLeadsPerMonth: 60,
    PricePerLiveTransfer: 93,
    TotalQualifiedLeadPrice: 5580,
    TotalPlatformPrice: 699,
    FinalPackagePrice: 6279,
  },
  {
    id: 12,
    AverageHomePricePoint: "$300K-$400K",
    PlanName: "Qualified 80",
    QualifiedLeadsPerMonth: 80,
    PricePerLiveTransfer: 90,
    TotalQualifiedLeadPrice: 7200,
    TotalPlatformPrice: 799,
    FinalPackagePrice: 7999,
  },
  {
    id: 13,
    AverageHomePricePoint: "$400K-$500K",
    PlanName: "Qualified 20",
    QualifiedLeadsPerMonth: 20,
    PricePerLiveTransfer: 109,
    TotalQualifiedLeadPrice: 2180,
    TotalPlatformPrice: 299,
    FinalPackagePrice: 2479,
  },
  {
    id: 14,
    AverageHomePricePoint: "$400K-$500K",
    PlanName: "Qualified 40",
    QualifiedLeadsPerMonth: 40,
    PricePerLiveTransfer: 106,
    TotalQualifiedLeadPrice: 4240,
    TotalPlatformPrice: 599,
    FinalPackagePrice: 4839,
  },
  {
    id: 15,
    AverageHomePricePoint: "$400K-$500K",
    PlanName: "Qualified 60",
    QualifiedLeadsPerMonth: 60,
    PricePerLiveTransfer: 102,
    TotalQualifiedLeadPrice: 6120,
    TotalPlatformPrice: 699,
    FinalPackagePrice: 6819,
  },
  {
    id: 16,
    AverageHomePricePoint: "$400K-$500K",
    PlanName: "Qualified 80",
    QualifiedLeadsPerMonth: 80,
    PricePerLiveTransfer: 99,
    TotalQualifiedLeadPrice: 7920,
    TotalPlatformPrice: 799,
    FinalPackagePrice: 8719,
  },
  {
    id: 17,
    AverageHomePricePoint: "$500K+",
    PlanName: "Qualified 20",
    QualifiedLeadsPerMonth: 20,
    PricePerLiveTransfer: 129,
    TotalQualifiedLeadPrice: 2580,
    TotalPlatformPrice: 299,
    FinalPackagePrice: 2879,
  },
  {
    id: 18,
    AverageHomePricePoint: "$500K+",
    PlanName: "Qualified 40",
    QualifiedLeadsPerMonth: 40,
    PricePerLiveTransfer: 125,
    TotalQualifiedLeadPrice: 5000,
    TotalPlatformPrice: 599,
    FinalPackagePrice: 5599,
  },
  {
    id: 19,
    AverageHomePricePoint: "$500K+",
    PlanName: "Qualified 60",
    QualifiedLeadsPerMonth: 60,
    PricePerLiveTransfer: 121,
    TotalQualifiedLeadPrice: 7260,
    TotalPlatformPrice: 699,
    FinalPackagePrice: 7959,
  },
  {
    id: 20,
    AverageHomePricePoint: "$500K+",
    PlanName: "Qualified 80",
    QualifiedLeadsPerMonth: 80,
    PricePerLiveTransfer: 117,
    TotalQualifiedLeadPrice: 9360,
    TotalPlatformPrice: 799,
    FinalPackagePrice: 10159,
  },
];
export default data;
